import js from "@eslint/js";
import globals from "globals";
import svelte from "eslint-plugin-svelte";
import svelteParser from "svelte-eslint-parser";
import sonarjs from "eslint-plugin-sonarjs";

export default [
  js.configs.recommended,
  ...svelte.configs["flat/recommended"],
  {
    files: ["**/*.svelte", "**/*.js"],
    languageOptions: {
      globals: {
        ...globals.browser,
      },
    },
  },
  {
    files: ["**/*.svelte"],
    languageOptions: {
      parser: svelteParser,
    },
  },
  {
    ignores: ["dist/", "node_modules/"],
  },
  {
    files: ["**/*.svelte", "**/*.js"],
    plugins: { sonarjs },
    rules: {
      ...sonarjs.configs.recommended.rules,
      // Svelte 5 requires `void $store.x` markers for dependency tracking.
      "sonarjs/void-use": "off",
      // {@render headerCell(...)} snippets have no return value — the rule
      // cannot understand snippets and flags them as empty-return usage.
      "sonarjs/no-use-of-empty-return-value": "off",
      // Only used to shuffle the header logo sprite.
      "sonarjs/pseudo-random": "off",
      // Ternary chains in Svelte tag attributes are an established idiom;
      // rewriting them hurts readability.
      "sonarjs/no-nested-conditional": "off",
      // Trailing-char strip patterns (/,+$/, /=+$/) over locally built
      // strings — no ReDoS risk.
      "sonarjs/super-linear-regex": "off",
      // Nested template literals in class/style composition.
      "sonarjs/no-nested-template-literals": "off",
      // Svelte attribute expressions inflate the metric; keep the rule as
      // warnings for genuinely large functions (pending refactors).
      "sonarjs/cognitive-complexity": ["warn", 25],
    },
  },
  {
    // schema-data.js is generated by go generate; the recommended sonarjs
    // rules don't fit its generated IIFE data table (false positives).
    // Placed last so these overrides win.
    files: ["src/schema-data.js"],
    rules: Object.fromEntries(
      Object.keys(sonarjs.configs.recommended.rules).map((r) => [r, "off"]),
    ),
  },
];
