name: Bangumi 重复条目检查
    
# 每周二21:30执行
on:
  schedule:
    - cron: '30 21 * * 2'  # 格式: 分 时 日 月 星期(0=周日, 2=周二)
  workflow_dispatch:  # 允许手动触发

jobs:
  check_duplicates:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取代码仓库
        uses: actions/checkout@v3
      
      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm beautifulsoup4
      
      - name: 下载最新Bangumi归档
        run: python download_bangumi_archive.py
      
      - name: 执行重复条目检查
        run: python check_reported_duplicates.py
      
      - name: 上传检查结果
        uses: actions/upload-artifact@v3
        with:
          name: duplicate-check-results
          path: duplicate_check_results.txt
      
      - name: 提交结果到仓库
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add duplicate_check_results.txt
          git commit -m "自动更新: 重复条目检查结果 $(date +'%Y-%m-%d')"
          git push
        continue-on-error: true  # 即使提交失败也不中断工作流
    
