name: Bangumi 重复条目检查
    
on:
  schedule:
    - cron: '30 21 * * 2'
  workflow_dispatch:

permissions:
  contents: write

env:
  REPORT_PAGES: >-
    https://bgm.tv/group/topic/431206,
    https://bgm.tv/group/topic/431529,
    https://bgm.tv/group/topic/423940

jobs:
  check_duplicates:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取代码仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm beautifulsoup4
      
      - name: 下载最新Bangumi归档
        run: python download_bangumi_archive.py
      
      - name: 执行重复条目检查
        run: python check_reported_duplicates.py
        env:
          REPORT_PAGES: ${{ env.REPORT_PAGES }}
          AUTO_MODE: "true"
      
      - name: 上传检查结果
        uses: actions/upload-artifact@v4
        with:
          name: duplicate-check-results
          path: duplicate_check_results.txt
      
      - name: 提交结果到仓库
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add duplicate_check_results.txt
          git commit -m "自动更新: 重复条目检查结果 $(date +'%Y-%m-%d')"
          git push
        continue-on-error: true
    
