name: 重复条目检查与别名表生成

on:
  schedule:
    - cron: '30 21 * * 2'
  workflow_dispatch:

permissions:
  contents: write

env:
  REPORT_PAGES: >-
    https://bgm.tv/group/topic/431206
  AUTO_MODE: "true"
  ALIAS_JSON: "person_alias.json"
  ALIAS_GZ: "person_alias.json.gz"
  RELEASE_NAME: "Person alias"
  TAG_NAME: ${{ github.event_name == 'schedule' ? format('{0:YYYYMMDD}', github.event.schedule.event_time) : format('{0:YYYYMMDD}', github.event.head_commit.timestamp) }}

jobs:
  check_and_generate:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm beautifulsoup4 bgm_tv_wiki

      - name: 下载Bangumi归档
        run: python download_bangumi_archive.py

      - name: 检查重复条目
        run: python find_duplicate_isbns.py

      - name: 生成Alias JSON
        run: python parse_bangumi_person_jsonlines.py  # 替换为你的实际脚本名

      - name: gzip压缩（直接指定输出）
        run: gzip -9 -c ${{ env.ALIAS_JSON }} > ${{ env.ALIAS_GZ }}  # 直接生成压缩文件

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: bangumi-results
          path: |
            duplicate_check_results.txt
            ${{ env.ALIAS_GZ }}

      - name: 提交重复检查结果
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add duplicate_check_results.txt
          git commit -m "更新重复检查结果 ${{ env.TAG_NAME }}"
          git push

      - name: 删旧Tag建新塘（日期格式）
        run: |
          git fetch --tags
          git tag -d ${{ env.TAG_NAME }} 2>/dev/null || true
          git push origin :refs/tags/${{ env.TAG_NAME }} 2>/dev/null || true
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: 发布/覆盖Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          body: "生成日期：${{ env.TAG_NAME }}"
          files: ${{ env.ALIAS_GZ }}
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
