name: validate person alias

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: 设置 uv
        uses: astral-sh/setup-uv@v5

      - name: 下载 Bangumi 归档
        run: bash bgq/download-archive.sh bangumi_archive

      - name: 生成别名 JSON
        run: uv run person_alias.py

      - name: gzip 压缩
        run: gzip -9 -c person_alias.json > person_alias.json.gz

      - name: 上传压缩产物
        uses: actions/upload-artifact@v5
        with:
          name: person_alias
          path: person_alias.json.gz
